In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')

In [4]:
Q = np.zeros([env.observation_space.n, env.action_space.n])
observation = env.reset()
env.render()
print('------------------------')
for i in range(env.action_space.n):
    action = i
    observation, reward, done, info = env.step(action)
    env.render()
    print('action: %d' %action)
    print('state : %d \ninfo : %.3f' %(observation,info['prob']))
    print('------------------------')
    observation = env.reset()


SFFF
FHFH
FFFH
HFFG
------------------------
  (Left)
SFFF
FHFH
FFFH
HFFG
action: 0
state : 4 
info : 0.333
------------------------
  (Down)
SFFF
FHFH
FFFH
HFFG
action: 1
state : 0 
info : 0.333
------------------------
  (Right)
SFFF
FHFH
FFFH
HFFG
action: 2
state : 4 
info : 0.333
------------------------
  (Up)
SFFF
FHFH
FFFH
HFFG
action: 3
state : 0 
info : 0.333
------------------------


In [5]:
# Set learning parameters
lr = .8   # learning rate
y = .95   # discount factor
num_episodes = 2000

#create lists to contain total rewards and steps per episode
rList = [] # reword list
# sList = [] # state list

In [6]:
for i in range(num_episodes):
    s = env.reset() # Reset environment and get first new observation
    rAll = 0        # total reward
    d = False       # end of precess
    j = 0           # step
#     print('------<initial state>-------')
#     env.render()
#     print('state : %d \ninfo : %.3f' %(s,info['prob']))
#     print('----------------------------')
    #The Q-Table learning algorithm
    while j < 100:
        j+=1
        
        # Choose an action by greedily (with noise) picking from Q table
        # 1/ (i+1) factor has the effect of cutting back on randomness
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))  
        
        #Get new state and reward of action an agent did from environment
        s1, r, d, info = env.step(a)
        
        # Update Q-Table with new knowledge(=reward)
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a]) 
        
        rAll += r # add reward 
        s = s1    # move to next state

        # Check some conditions in console
#         env.render()
#         print('step : ')
#         print('action: %d' %a)
#         print('state : %d \ninfo : %.3f' %(s,info['prob']))
#         print('----------------------------')
        
        # check the end of process
        if d == True:
#             if rAll == 1:
#                 print('Arrive at goal State!\n')

#             else:
#                 print('Arrive at hole. T.T\n')
            break
    #jList.append(j)
    rList.append(rAll)

print ("Score over time: " +  str(sum(rList)/num_episodes))

print ("Final Q-Table Values")
print (np.round(Q,3))

Score over time: 0.566
Final Q-Table Values
[[0.4   0.007 0.012 0.002]
 [0.002 0.001 0.    0.009]
 [0.001 0.    0.021 0.001]
 [0.    0.    0.    0.017]
 [0.217 0.001 0.001 0.   ]
 [0.    0.    0.    0.   ]
 [0.001 0.    0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.009 0.004 0.    0.102]
 [0.    0.242 0.    0.002]
 [0.007 0.    0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.002 0.001 0.103 0.001]
 [0.    0.    0.811 0.   ]
 [0.    0.    0.    0.   ]]


In [7]:
action_at_state=[]
action_set=['Left', 'Down', 'Right', 'Up']
for i in range(len(Q)):
    if np.sum(Q[i]) == 0:
        action_at_state.append('hole or goal state')
    else:
        idx=np.argmax(Q[i])
        action_at_state.append(action_set[idx])
print ("at state, the agent move : ")
print (action_at_state)

at state, the agent move : 
['Left', 'Up', 'Right', 'Up', 'Left', 'hole or goal state', 'Left', 'hole or goal state', 'Up', 'Down', 'Left', 'hole or goal state', 'hole or goal state', 'Right', 'Right', 'hole or goal state']
