In [2]:
import numpy as np
import _pickle
import tensorflow as tf
%matplotlib inline
import matplotlib.pyplot as plt
import math

In [3]:
# Load the CartPole Env.
import gym
env = gym.make('CartPole-v0')

In [4]:
from gym import logger as gymlogger
from gym.wrappers import Monitor 
gymlogger.set_level(40) #error only 
import glob 
import io 
import base64 
from IPython.display import HTML 
from IPython import display as ipythondisplay 

""" 
Utility functions to enable video recording of gym environment and displaying it 
To enable video, just do "env = wrap_env(env)"" 
""" 

def show_video(): 
    mp4list = glob.glob('video/*.mp4') 
    if len(mp4list) > 0: 
        mp4 = mp4list[0] 
        video = io.open(mp4, 'r+b').read() 
        encoded = base64.b64encode(video) 
        ipythondisplay.display(HTML(data='''<video alt="test" autoplay loop controls style="height: 400px;"> <source src="data:video/mp4;base64,{0}" type="video/mp4" /> </video>'''.format(encoded.decode('ascii')))) 
    else:
        print("Could not find video") 
        
def wrap_env(env):
    env = Monitor(env, './video', force=True)
    return env 
        
from pyvirtualdisplay import Display 
display = Display(visible=0, size=(1400, 900)) 
display.start()

env = wrap_env(gym.make('CartPole-v0'))
observation = env.reset()
random_episodes = 0
reward_sum = 0
total_reward = []
while random_episodes < 20:
    env.render()
    action = env.action_space.sample()
    print(observation, action)
    observation, reward, done, _ = env.step(action)
    reward_sum += reward
    if done:
        random_episodes += 1
        total_reward.append(reward_sum)
        print("Reward for this episode was: {}, Average reward for episode so far is: {}".format(reward_sum, np.round(np.mean(total_reward),1)))
        reward_sum = 0
        env.reset()
env.close()
show_video()


[-0.03876151 -0.02615055 -0.02544958 -0.04944212] 0
[-0.03928452 -0.22089851 -0.02643842  0.23510385] 0
[-0.04370249 -0.41563294 -0.02173634  0.51933143] 0
[-0.05201515 -0.61044224 -0.01134971  0.80508637] 0
[-0.064224   -0.80540678  0.00475201  1.09417759] 1
[-0.08033213 -0.61034775  0.02663557  0.80298944] 0
[-0.09253909 -0.80582461  0.04269535  1.10393066] 0
[-0.10865558 -1.00148131  0.06477397  1.40969687] 0
[-0.12868521 -1.19734407  0.0929679   1.72190513] 1
[-0.15263209 -1.00340151  0.12740601  1.45954079] 0
[-0.17270012 -1.19983482  0.15659682  1.78915867] 1
[-0.19669682 -1.00677869  0.19238     1.54896943] 1
Reward for this episode was: 12.0, Average reward for episode so far is: 12.0
[-0.21683239 -0.81441516  0.22335938  1.32195871] 1
[-0.02099217  0.2009561   0.01744014 -0.27415315] 0
[-0.01697305  0.00558971  0.01195708  0.02397901] 0
[-0.01686126 -0.18970166  0.01243666  0.32041042] 1
[-0.02065529  0.00524099  0.01884487  0.03167534] 1
[-0.02055047  0.2000877   0.01947837 -